baseURL = "https://arionmiles.me/"
languageCode = "en-us"
title = "Kanishk Singh"
theme = "hugo-ink"
paginate = 5

# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
googleAnalytics = "UA-29508202-2"

disqusShortname = "arionmiles"

[params]
	# Blog subtitle which appears below blog title. Supports markdown.
	subtitle = "Runes of Undocumented Code"

	# Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
	excludedTypes = ["page"]
	mainSections = ["post"]

	# Content types which are excludes Disqus comments (Optional). Defaults to ["page"]
	disableDisqusTypes = ["page"]

	# If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
	featherIconsCDN = true

	# Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
    mode = "dark" # "dark" or "auto"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/ArionMiles"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:kanishk@arionmiles.me"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/Arion_Miles"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/arionmiles/"

# Enable tags.
[taxonomies]
   tag = "tags"
